=== PaulStepanov/EPAM-courses-authumn-2016/ThirdTask/resources/xmls/xsdSheme.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="paper">
        <xs:complexType>
            <xs:sequence maxOccurs="unbounded">
                <xs:element name="periodical">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:ID" name="title"/>
                            <xs:element name="type">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="newspaper"/>
                                        <xs:enumeration value="magazine"/>
                                        <xs:enumeration value="booklet"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="monthly">
                                <xs:complexType>
                                    <xs:attribute name="value" type="xs:boolean" use="required"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="chars">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="colored">
                                            <xs:complexType>
                                                <xs:attribute type="xs:boolean" name="value"
                                                              use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="size">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:integer">
                                                    <xs:minInclusive value="1"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="gloss">
                                            <xs:complexType>
                                                <xs:attribute type="xs:boolean" name="value"
                                                              use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="hasIndex">
                                            <xs:complexType>
                                                <xs:attribute type="xs:boolean" name="value" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== PaulStepanov/EPAM-courses-authumn-2016/ThirdTask/resources/xmls/xmlData.xml
<?xml version="1.0" encoding="UTF-8" ?>
<paper
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="xsdSheme.xsd">
    <periodical>
        <title>
            MyTitle
        </title>
        <type>newspaper</type>
        <monthly value="true"/>
        <chars>
            <colored value="true"/>
            <size>15</size>
            <gloss value="true"/>
            <hasIndex value="true"/>
        </chars>
    </periodical>
    <periodical>
        <title>Mytitle1</title>
        <type>booklet</type>
        <monthly value="true"/>
        <chars>
            <colored value="false"/>
            <size>18</size>
            <gloss value="true"/>
            <hasIndex value="false"/>
        </chars>
    </periodical>
    <periodical>
        <title>Mytitle2</title>
        <type>magazine</type>
        <monthly value="true"/>
        <chars>
            <colored value="true"/>
            <size>20</size>
            <gloss value="true"/>
            <hasIndex value="true"/>
        </chars>
    </periodical>


</paper>
